    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      run_autograding:
        name: Autograding
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Autograding
            uses: education/autograding@v1

          - name: Cleanup
            if: always()
            run: rm -rf ./MNIST ./MNIST_image_folder